apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: redmine-backendconfig
  namespace: redmine-namespace
spec:
  healthCheck:
    checkIntervalSec: 15
    type: HTTP
    requestPath: /login
