apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: redmine-backendconfig
  namespace: redmine-namespace
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 60
